// <auto-generated />
using System;
using HamsterApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamsterApp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HamsterApp.Entities.Models.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e7eabebd-e10c-4da9-b6aa-2db9cad6b84d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "007a69dc-0618-467f-beb8-9a2ffd122dc1",
                            Email = "admin@hamsters.com",
                            EmailConfirmed = false,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HAMSTERS.COM",
                            NormalizedUserName = "ADMIN@HAMSTERS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEZerZiiNkXPwGox76UoWExZaV3sjq+cfkBIB2rMGMuuOukQewS1mMlyYzRxxJi5+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "98059ea3-da47-4047-9948-05d72d8de626",
                            TwoFactorEnabled = false,
                            UserName = "admin@hamsters.com"
                        },
                        new
                        {
                            Id = "087f2124-f507-4642-a8f7-84442abb3d70",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f306d70-d01c-4354-8316-9bad15223537",
                            Email = "user@hamsters.com",
                            EmailConfirmed = false,
                            FirstName = "System",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@HAMSTERS.COM",
                            NormalizedUserName = "USER@HAMSTERS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFgC2477yCNO/FaVpjivgagYx15dF/fwXU5gL8vCj6mkMqj8E8aQzvAJP9nj1gnKLA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ecbfb0fc-cdfc-44bc-b3b9-fefa166db28c",
                            TwoFactorEnabled = false,
                            UserName = "user@hamsters.com"
                        });
                });

            modelBuilder.Entity("HamsterApp.Entities.Models.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FavFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Games")
                        .HasColumnType("int");

                    b.Property<string>("ImgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Loves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            FavFood = "Camembert",
                            Games = 0,
                            ImgName = "/images/hamster-1.jpg",
                            Losses = 0,
                            Loves = "His Master",
                            Name = "Ebichu",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 3,
                            FavFood = "Pizza",
                            Games = 0,
                            ImgName = "/images/hamster-2.jpg",
                            Losses = 0,
                            Loves = "Climbing",
                            Name = "Oliver",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 2,
                            FavFood = "Mud",
                            Games = 0,
                            ImgName = "/images/hamster-3.jpg",
                            Losses = 0,
                            Loves = "Playing Football",
                            Name = "Iver",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            Age = 1,
                            FavFood = "Olives",
                            Games = 0,
                            ImgName = "/images/hamster-4.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Urban",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 2,
                            FavFood = "Tortila",
                            Games = 0,
                            ImgName = "/images/hamster-5.jpg",
                            Losses = 0,
                            Loves = "Fighting",
                            Name = "Lisa",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            FavFood = "Salad",
                            Games = 0,
                            ImgName = "/images/hamster-6.jpg",
                            Losses = 0,
                            Loves = "Working out",
                            Name = "Thomas",
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            Age = 3,
                            FavFood = "Flesh",
                            Games = 0,
                            ImgName = "/images/hamster-7.jpg",
                            Losses = 0,
                            Loves = "Chaos",
                            Name = "Renya",
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            Age = 2,
                            FavFood = "Naan",
                            Games = 0,
                            ImgName = "/images/hamster-8.jpg",
                            Losses = 0,
                            Loves = "Trains",
                            Name = "Valvet",
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            Age = 1,
                            FavFood = "Poptarts",
                            Games = 0,
                            ImgName = "/images/hamster-9.jpg",
                            Losses = 0,
                            Loves = "America",
                            Name = "Cece",
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            Age = 2,
                            FavFood = "Potatoes",
                            Games = 0,
                            ImgName = "/images/hamster-10.jpg",
                            Losses = 0,
                            Loves = "Drama",
                            Name = "Poppy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 11,
                            Age = 3,
                            FavFood = "Plastic",
                            Games = 0,
                            ImgName = "/images/hamster-11.jpg",
                            Losses = 0,
                            Loves = "Losing",
                            Name = "Ehmberg",
                            Wins = 0
                        },
                        new
                        {
                            Id = 12,
                            Age = 2,
                            FavFood = "Ramen",
                            Games = 0,
                            ImgName = "/images/hamster-12.jpg",
                            Losses = 0,
                            Loves = "Subways",
                            Name = "Svahlberg",
                            Wins = 0
                        },
                        new
                        {
                            Id = 13,
                            Age = 3,
                            FavFood = "Tacos",
                            Games = 0,
                            ImgName = "/images/hamster-13.jpg",
                            Losses = 0,
                            Loves = "Gaining weight",
                            Name = "Ohm",
                            Wins = 0
                        },
                        new
                        {
                            Id = 14,
                            Age = 1,
                            FavFood = "Meatballs",
                            Games = 0,
                            ImgName = "/images/hamster-14.jpg",
                            Losses = 0,
                            Loves = "Sitting",
                            Name = "Bert",
                            Wins = 0
                        },
                        new
                        {
                            Id = 15,
                            Age = 1,
                            FavFood = "Salmon",
                            Games = 0,
                            ImgName = "/images/hamster-15.jpg",
                            Losses = 0,
                            Loves = "Hunting",
                            Name = "Fredrik",
                            Wins = 0
                        },
                        new
                        {
                            Id = 16,
                            Age = 1,
                            FavFood = "Tomatoes",
                            Games = 0,
                            ImgName = "/images/hamster-16.jpg",
                            Losses = 0,
                            Loves = "Swimming",
                            Name = "Ida",
                            Wins = 0
                        },
                        new
                        {
                            Id = 17,
                            Age = 1,
                            FavFood = "Chocolate",
                            Games = 0,
                            ImgName = "/images/hamster-17.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Name = "Karl",
                            Wins = 0
                        },
                        new
                        {
                            Id = 18,
                            Age = 1,
                            FavFood = "Sourcream",
                            Games = 0,
                            ImgName = "/images/hamster-18.jpg",
                            Losses = 0,
                            Loves = "Walking",
                            Name = "Linn",
                            Wins = 0
                        },
                        new
                        {
                            Id = 19,
                            Age = 1,
                            FavFood = "Carrots",
                            Games = 0,
                            ImgName = "/images/hamster-19.jpg",
                            Losses = 0,
                            Loves = "Winning",
                            Name = "Ewa",
                            Wins = 0
                        },
                        new
                        {
                            Id = 20,
                            Age = 1,
                            FavFood = "Beans",
                            Games = 0,
                            ImgName = "/images/hamster-20.jpg",
                            Losses = 0,
                            Loves = "Farting",
                            Name = "Ingrid",
                            Wins = 0
                        },
                        new
                        {
                            Id = 21,
                            Age = 1,
                            FavFood = "Burritos",
                            Games = 0,
                            ImgName = "/images/hamster-21.jpg",
                            Losses = 0,
                            Loves = "Dancing",
                            Name = "Daniel",
                            Wins = 0
                        },
                        new
                        {
                            Id = 22,
                            Age = 1,
                            FavFood = "Garlic",
                            Games = 0,
                            ImgName = "/images/hamster-22.jpg",
                            Losses = 0,
                            Loves = "Breathing",
                            Name = "Nizz",
                            Wins = 0
                        },
                        new
                        {
                            Id = 23,
                            Age = 1,
                            FavFood = "Oranges",
                            Games = 0,
                            ImgName = "/images/hamster-23.jpg",
                            Losses = 0,
                            Loves = "Friends",
                            Name = "Gustaf",
                            Wins = 0
                        },
                        new
                        {
                            Id = 24,
                            Age = 3,
                            FavFood = "Lemon",
                            Games = 0,
                            ImgName = "/images/hamster-24.jpg",
                            Losses = 0,
                            Loves = "Family",
                            Name = "Tiffany",
                            Wins = 0
                        },
                        new
                        {
                            Id = 25,
                            Age = 1,
                            FavFood = "Pancakes",
                            Games = 0,
                            ImgName = "/images/hamster-25.jpg",
                            Losses = 0,
                            Loves = "Baking",
                            Name = "Jake",
                            Wins = 0
                        },
                        new
                        {
                            Id = 26,
                            Age = 1,
                            FavFood = "Sandwiches",
                            Games = 0,
                            ImgName = "/images/hamster-26.jpg",
                            Losses = 0,
                            Loves = "Adventure",
                            Name = "Finn",
                            Wins = 0
                        },
                        new
                        {
                            Id = 27,
                            Age = 1,
                            FavFood = "Spaghetti",
                            Games = 0,
                            ImgName = "/images/hamster-27.jpg",
                            Losses = 0,
                            Loves = "Opera",
                            Name = "Jarvis",
                            Wins = 0
                        },
                        new
                        {
                            Id = 28,
                            Age = 1,
                            FavFood = "Pears",
                            Games = 0,
                            ImgName = "/images/hamster-28.jpg",
                            Losses = 0,
                            Loves = "Music",
                            Name = "Peppy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 29,
                            Age = 1,
                            FavFood = "Curry",
                            Games = 0,
                            ImgName = "/images/hamster-29.jpg",
                            Losses = 0,
                            Loves = "The Sun",
                            Name = "Hampus",
                            Wins = 0
                        },
                        new
                        {
                            Id = 30,
                            Age = 1,
                            FavFood = "Dumplings",
                            Games = 0,
                            ImgName = "/images/hamster-30.jpg",
                            Losses = 0,
                            Loves = "Work",
                            Name = "Fiona",
                            Wins = 0
                        },
                        new
                        {
                            Id = 31,
                            Age = 1,
                            FavFood = "Gyoza",
                            Games = 0,
                            ImgName = "/images/hamster-31.jpg",
                            Losses = 0,
                            Loves = "Traveling",
                            Name = "Lisabell",
                            Wins = 0
                        },
                        new
                        {
                            Id = 32,
                            Age = 1,
                            FavFood = "Fish",
                            Games = 0,
                            ImgName = "/images/hamster-32.jpg",
                            Losses = 0,
                            Loves = "Fishing",
                            Name = "Olivia",
                            Wins = 0
                        },
                        new
                        {
                            Id = 33,
                            Age = 1,
                            FavFood = "Melons",
                            Games = 0,
                            ImgName = "/images/hamster-33.jpg",
                            Losses = 0,
                            Loves = "Gardening",
                            Name = "Cedric",
                            Wins = 0
                        },
                        new
                        {
                            Id = 34,
                            Age = 1,
                            FavFood = "Chili con Carne",
                            Games = 0,
                            ImgName = "/images/hamster-34.jpg",
                            Losses = 0,
                            Loves = "Haircuts",
                            Name = "Hamil",
                            Wins = 0
                        },
                        new
                        {
                            Id = 35,
                            Age = 3,
                            FavFood = "Pupusas",
                            Games = 0,
                            ImgName = "/images/hamster-35.jpg",
                            Losses = 0,
                            Loves = "Sunbathing",
                            Name = "Julia",
                            Wins = 0
                        },
                        new
                        {
                            Id = 36,
                            Age = 2,
                            FavFood = "Cakes",
                            Games = 0,
                            ImgName = "/images/hamster-36.jpg",
                            Losses = 0,
                            Loves = "Exercise",
                            Name = "Ana-Maria",
                            Wins = 0
                        },
                        new
                        {
                            Id = 37,
                            Age = 3,
                            FavFood = "Popcorn",
                            Games = 0,
                            ImgName = "/images/hamster-37.jpg",
                            Losses = 0,
                            Loves = "Hunting",
                            Name = "Sammy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 38,
                            Age = 1,
                            FavFood = "Fried-Chicken",
                            Games = 0,
                            ImgName = "/images/hamster-38.jpg",
                            Losses = 0,
                            Loves = "Brewing",
                            Name = "Alex",
                            Wins = 0
                        },
                        new
                        {
                            Id = 39,
                            Age = 1,
                            FavFood = "Corn",
                            Games = 0,
                            ImgName = "/images/hamster-39.jpg",
                            Losses = 0,
                            Loves = "Reading",
                            Name = "Sandy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 40,
                            Age = 3,
                            FavFood = "Hamsters",
                            Games = 0,
                            ImgName = "/images/hamster-40.jpg",
                            Losses = 0,
                            Loves = "Being Crazy",
                            Name = "Felicia",
                            Wins = 0
                        });
                });

            modelBuilder.Entity("HamsterApp.Entities.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("HamsterId")
                        .HasColumnType("int");

                    b.Property<int>("LoseId")
                        .HasColumnType("int");

                    b.Property<int>("WinId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HamsterId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3845d87b-b230-41ff-a1a7-84bbd7ec821d",
                            ConcurrencyStamp = "d9c60804-68c0-4ea8-b889-370374cfb43e",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "985f4930-21ad-4249-abaf-e4251b1553d9",
                            ConcurrencyStamp = "99d7ed20-060f-4ca4-9406-17c5cde7e80f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "087f2124-f507-4642-a8f7-84442abb3d70",
                            RoleId = "3845d87b-b230-41ff-a1a7-84bbd7ec821d"
                        },
                        new
                        {
                            UserId = "e7eabebd-e10c-4da9-b6aa-2db9cad6b84d",
                            RoleId = "985f4930-21ad-4249-abaf-e4251b1553d9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HamsterApp.Entities.Models.Match", b =>
                {
                    b.HasOne("HamsterApp.Entities.Models.Hamster", "Hamster")
                        .WithMany("Matches")
                        .HasForeignKey("HamsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hamster");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HamsterApp.Entities.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HamsterApp.Entities.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HamsterApp.Entities.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HamsterApp.Entities.Models.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HamsterApp.Entities.Models.Hamster", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
